### ISSUE TITLE
Incorrect FSF address in COPYING

### ISSUE THREAD

**Issue by spinl0ck** [BR903/ELFkickers#16]
Hello.
I'm trying to build a RPM package for ELFkickers, but the rpmlint complains about the incorrect fsf address.

`ELFkickers.x86_64: E: incorrect-fsf-address /usr/share/licenses/ELFkickers/COPYING`

[https://fedoraproject.org/wiki/Common_Rpmlint_issues#incorrect-fsf-address](url) sais I should report this.

The current address is [https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt](url)

`51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA`

Please change it.

**Comment by BR903** [comment]
Fixed in v3.2.
